-- Heliopolis schema
-- Extensions (pg_net and pg_cron are enabled via Supabase dashboard)

-- ============================================================
-- Tables
-- ============================================================

-- Wallets: core table for tracked Solana wallets
CREATE TABLE public.wallets (
  address              text PRIMARY KEY,
  txn_count            integer        NOT NULL DEFAULT 0,
  volume_traded_sol    double precision NOT NULL DEFAULT 0,
  fees_paid_sol        double precision NOT NULL DEFAULT 0,
  wallet_age_days      integer        NOT NULL DEFAULT 0,
  first_tx_at          timestamptz,
  updated_at           timestamptz    NOT NULL DEFAULT now(),
  ingestion_status     text           NOT NULL DEFAULT 'complete'
    CHECK (ingestion_status IN ('queued','processing','complete','failed')),
  block_row            smallint,
  block_col            smallint,
  local_slot           smallint,
  unique_tokens_swapped integer      DEFAULT 0,
  latest_tx_at         timestamptz,
  traded_token_mints   jsonb,
  identity_name        text,
  identity_type        text,
  identity_category    text
);

CREATE UNIQUE INDEX wallets_city_position_unique
  ON public.wallets (block_row, block_col, local_slot);

CREATE INDEX idx_wallets_placed
  ON public.wallets (block_row, block_col)
  WHERE block_row IS NOT NULL;

CREATE INDEX idx_wallets_unplaced
  ON public.wallets (ingestion_status)
  WHERE ingestion_status = 'complete' AND block_row IS NULL;

-- Profiles: linked user accounts (X / Phantom)
CREATE TABLE public.profiles (
  id             uuid PRIMARY KEY REFERENCES auth.users (id),
  wallet_address text UNIQUE,
  x_username     text,
  x_avatar_url   text,
  created_at     timestamptz DEFAULT now(),
  updated_at     timestamptz DEFAULT now()
);

-- Ingestion queue: background wallet data fetching
CREATE TABLE public.ingestion_queue (
  address          text PRIMARY KEY REFERENCES public.wallets (address),
  status           text    NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','processing','complete','failed')),
  pagination_token text,
  error_message    text,
  pages_fetched    integer NOT NULL DEFAULT 0,
  txns_fetched     integer NOT NULL DEFAULT 0,
  retry_count      integer NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  claim_nonce      uuid,
  slices           jsonb
);

CREATE INDEX idx_ingestion_queue_status
  ON public.ingestion_queue (status, created_at);

-- Block spiral order: deterministic city layout
CREATE TABLE public.block_spiral_order (
  spiral_index smallint PRIMARY KEY,
  block_row    smallint NOT NULL,
  block_col    smallint NOT NULL,
  is_park      boolean  NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX block_spiral_order_block_row_block_col_key
  ON public.block_spiral_order (block_row, block_col);

-- City snapshots: periodic aggregate stats
CREATE TABLE public.city_snapshots (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at          timestamptz NOT NULL DEFAULT now(),
  total_wallets       integer NOT NULL DEFAULT 0,
  total_txn_count     bigint  NOT NULL DEFAULT 0,
  total_volume_sol    numeric NOT NULL DEFAULT 0,
  total_fees_sol      numeric NOT NULL DEFAULT 0,
  avg_wallet_age_days numeric NOT NULL DEFAULT 0,
  occupied_blocks     integer NOT NULL DEFAULT 0
);

CREATE INDEX idx_city_snapshots_created_at
  ON public.city_snapshots (created_at DESC);

-- Swap events: real-time swap transactions from Helius webhook
CREATE TABLE public.swap_events (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_address  text    NOT NULL,
  signature       text    NOT NULL UNIQUE,
  token_in        text,
  token_out       text,
  amount_sol      numeric,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_swap_events_created
  ON public.swap_events (created_at);

-- Bot wallets: cached bot detection results
CREATE TABLE public.bot_wallets (
  address     text PRIMARY KEY,
  reason      text,
  detected_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- Row Level Security
-- ============================================================

ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingestion_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_spiral_order ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.city_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swap_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_wallets ENABLE ROW LEVEL SECURITY;

-- Wallets: public read, service-role write
CREATE POLICY wallets_read_all ON public.wallets
  FOR SELECT USING (true);
CREATE POLICY wallets_insert_service ON public.wallets
  FOR INSERT WITH CHECK (true);
CREATE POLICY wallets_update_service ON public.wallets
  FOR UPDATE USING (true);

-- Profiles
CREATE POLICY "Profiles are viewable by everyone" ON public.profiles
  FOR SELECT USING (true);
CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Swap events: public read (needed for Supabase Realtime)
CREATE POLICY "Allow public read" ON public.swap_events
  FOR SELECT USING (true);

-- City snapshots: public read
CREATE POLICY "Public read access" ON public.city_snapshots
  FOR SELECT USING (true);

-- ============================================================
-- Realtime
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.swap_events;
